[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "gde"
version = "0.1.0"
description = "Goldwait Decision Engine (GDE) powering GWX"
authors = [{name="Goldwait Capital"}]
requires-python = ">=3.11"
dependencies = ["numpy>=2.1.0","pandas>=2.2.0"]
